// Code generated by protoc-gen-go.
// source: bag.proto
// DO NOT EDIT!

/*
Package GxProto is a generated protocol buffer package.

It is generated from these files:
	bag.proto
	card.proto
	chapter.proto
	common.proto
	equipment.proto
	friend.proto
	login.proto
	macros.proto
	mail.proto
	role.proto
	server.proto
	task.proto

It has these top-level messages:
	UseItemReq
	UseItemRsp
	SellItemReq
	SellItemRsp
	OrderBagRsp
	ExpandBagRsp
	FuseCardReq
	FuseCardRsp
	DecomposeCardReq
	DecomposeCardRsp
	NewFightCardBagReq
	NewFightCardBagRsp
	DelFightCardBagReq
	DelFightCardBagRsp
	AddFightCardReq
	DelFightCardReq
	ExtractCardReq
	ExtractCardRsp
	ReceiveCardReq
	ReceiveCardRsp
	ExtractSkillCardReq
	ExtractSkillCardRsp
	GetBuyCardCardInfoRsp
	PbLevelInfo
	GetLevelInfoReq
	GetLevelInfoRsp
	PbPointInfo
	GetPointInfoReq
	GetPointInfoRsp
	ChapterShuffleRsp
	ChapterBattleBeginReq
	ChapterBattleBeginRsp
	ChapterBattleEndReq
	ChapterBattleEndRsp
	PlayerRaw
	GameSrvInfo
	LoginRspInfo
	RoleCommonInfo
	RoleOtherInfo
	PbItemInfo
	PbBagCellInfo
	PbBagInfo
	PbCardBagInfo
	PbFightCardBagInfo
	RequestInfo
	PbCellInfo
	RoleChangeInfo
	PbBuyCardInfo
	RespondInfo
	StrengthenEquipmentReq
	StrengthenEquipmentRsp
	ReplaceEquipmentReq
	ReplaceEquipmentRsp
	UnloadEquipmentReq
	UnloadEquipmentRsp
	GetFriendRsp
	GetReferrerRsp
	AddFriendReq
	AddFriendNotify
	DealFriendReq
	DealFriendNotify
	DeleteFriendReq
	DeleteFriendNotify
	FriendSendReq
	FriendSendNotify
	FriendRecvReq
	FriendRecvRsp
	FriendInfoChangeNotify
	LoginServerReq
	LoginServerRsp
	GetGatesInfoRsp
	PbMailInfo
	GetMailListRsp
	ReadMailReq
	GetMailItemReq
	GetMailItemRsp
	NewMailNotify
	GetRoleListReq
	GetRoleListRsp
	SelectRoleReq
	SelectRoleRsp
	CreateRoleReq
	CreateRoleRsp
	PowerAddNotify
	BuyPowerRsp
	GetFreePowerRsp
	InfoChangeNotify
	SendChatReq
	NewChatNotify
	SelectVocationReq
	GetRoleFightInfoReq
	GetRoleFightInfoRsp
	RechargeReq
	RechargeNotify
	ServerConnectGateReq
	ClientLogoutNotify
	AdminReq
	AdminRsp
	TaskState
	PbTaskInfo
	GetTasksListRsp
	CompleteTaskRsp
	ReceiveTaskRewardReq
	ReceiveTaskRewardRsp
*/
package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 使用道具请求
type UseItemReq struct {
	Indx             *int32 `protobuf:"varint,1,opt,name=indx" json:"indx,omitempty"`
	Cnt              *int32 `protobuf:"varint,2,opt,name=cnt" json:"cnt,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UseItemReq) Reset()         { *m = UseItemReq{} }
func (m *UseItemReq) String() string { return proto.CompactTextString(m) }
func (*UseItemReq) ProtoMessage()    {}

func (m *UseItemReq) GetIndx() int32 {
	if m != nil && m.Indx != nil {
		return *m.Indx
	}
	return 0
}

func (m *UseItemReq) GetCnt() int32 {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return 0
}

// 使用道具响应
type UseItemRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *UseItemRsp) Reset()         { *m = UseItemRsp{} }
func (m *UseItemRsp) String() string { return proto.CompactTextString(m) }
func (*UseItemRsp) ProtoMessage()    {}

func (m *UseItemRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 出售道具请求
type SellItemReq struct {
	Indx             *int32 `protobuf:"varint,1,opt,name=indx" json:"indx,omitempty"`
	Cnt              *int32 `protobuf:"varint,2,opt,name=cnt" json:"cnt,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SellItemReq) Reset()         { *m = SellItemReq{} }
func (m *SellItemReq) String() string { return proto.CompactTextString(m) }
func (*SellItemReq) ProtoMessage()    {}

func (m *SellItemReq) GetIndx() int32 {
	if m != nil && m.Indx != nil {
		return *m.Indx
	}
	return 0
}

func (m *SellItemReq) GetCnt() int32 {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return 0
}

// 出售道具响应
type SellItemRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SellItemRsp) Reset()         { *m = SellItemRsp{} }
func (m *SellItemRsp) String() string { return proto.CompactTextString(m) }
func (*SellItemRsp) ProtoMessage()    {}

func (m *SellItemRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 整理背包请求
// 整理背包响应
type OrderBagRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Bag              *PbBagInfo   `protobuf:"bytes,2,opt,name=bag" json:"bag,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *OrderBagRsp) Reset()         { *m = OrderBagRsp{} }
func (m *OrderBagRsp) String() string { return proto.CompactTextString(m) }
func (*OrderBagRsp) ProtoMessage()    {}

func (m *OrderBagRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *OrderBagRsp) GetBag() *PbBagInfo {
	if m != nil {
		return m.Bag
	}
	return nil
}

// 扩充背包请求
// 扩充背包响应
type ExpandBagRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	BuyCount         *int32       `protobuf:"varint,2,opt,name=buyCount" json:"buyCount,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExpandBagRsp) Reset()         { *m = ExpandBagRsp{} }
func (m *ExpandBagRsp) String() string { return proto.CompactTextString(m) }
func (*ExpandBagRsp) ProtoMessage()    {}

func (m *ExpandBagRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ExpandBagRsp) GetBuyCount() int32 {
	if m != nil && m.BuyCount != nil {
		return *m.BuyCount
	}
	return 0
}
