// Code generated by protoc-gen-go.
// source: card.proto
// DO NOT EDIT!

package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 融合卡牌请求
type FuseCardReq struct {
	Card             *PbItemInfo `protobuf:"bytes,1,opt,name=card" json:"card,omitempty"`
	UseGold          *int32      `protobuf:"varint,2,opt,name=useGold" json:"useGold,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FuseCardReq) Reset()         { *m = FuseCardReq{} }
func (m *FuseCardReq) String() string { return proto.CompactTextString(m) }
func (*FuseCardReq) ProtoMessage()    {}

func (m *FuseCardReq) GetCard() *PbItemInfo {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *FuseCardReq) GetUseGold() int32 {
	if m != nil && m.UseGold != nil {
		return *m.UseGold
	}
	return 0
}

// 融合卡牌响应
type FuseCardRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Success          *int32       `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FuseCardRsp) Reset()         { *m = FuseCardRsp{} }
func (m *FuseCardRsp) String() string { return proto.CompactTextString(m) }
func (*FuseCardRsp) ProtoMessage()    {}

func (m *FuseCardRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *FuseCardRsp) GetSuccess() int32 {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return 0
}

// 分解卡牌请求
type DecomposeCardReq struct {
	Card             []*PbItemInfo `protobuf:"bytes,1,rep,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *DecomposeCardReq) Reset()         { *m = DecomposeCardReq{} }
func (m *DecomposeCardReq) String() string { return proto.CompactTextString(m) }
func (*DecomposeCardReq) ProtoMessage()    {}

func (m *DecomposeCardReq) GetCard() []*PbItemInfo {
	if m != nil {
		return m.Card
	}
	return nil
}

// 分解卡牌响应
type DecomposeCardRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DecomposeCardRsp) Reset()         { *m = DecomposeCardRsp{} }
func (m *DecomposeCardRsp) String() string { return proto.CompactTextString(m) }
func (*DecomposeCardRsp) ProtoMessage()    {}

func (m *DecomposeCardRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 新建卡组请求
type NewFightCardBagReq struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NewFightCardBagReq) Reset()         { *m = NewFightCardBagReq{} }
func (m *NewFightCardBagReq) String() string { return proto.CompactTextString(m) }
func (*NewFightCardBagReq) ProtoMessage()    {}

func (m *NewFightCardBagReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// 新建卡组响应
type NewFightCardBagRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Id               *int32       `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Ts               *int64       `protobuf:"varint,3,opt,name=ts" json:"ts,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NewFightCardBagRsp) Reset()         { *m = NewFightCardBagRsp{} }
func (m *NewFightCardBagRsp) String() string { return proto.CompactTextString(m) }
func (*NewFightCardBagRsp) ProtoMessage()    {}

func (m *NewFightCardBagRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *NewFightCardBagRsp) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *NewFightCardBagRsp) GetTs() int64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

// 删除卡组请求
type DelFightCardBagReq struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DelFightCardBagReq) Reset()         { *m = DelFightCardBagReq{} }
func (m *DelFightCardBagReq) String() string { return proto.CompactTextString(m) }
func (*DelFightCardBagReq) ProtoMessage()    {}

func (m *DelFightCardBagReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 删除卡组响应
type DelFightCardBagRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DelFightCardBagRsp) Reset()         { *m = DelFightCardBagRsp{} }
func (m *DelFightCardBagRsp) String() string { return proto.CompactTextString(m) }
func (*DelFightCardBagRsp) ProtoMessage()    {}

func (m *DelFightCardBagRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 添加卡牌到卡组请求
type AddFightCardReq struct {
	CardId           *int32        `protobuf:"varint,2,opt,name=cardId" json:"cardId,omitempty"`
	Card             []*PbItemInfo `protobuf:"bytes,1,rep,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *AddFightCardReq) Reset()         { *m = AddFightCardReq{} }
func (m *AddFightCardReq) String() string { return proto.CompactTextString(m) }
func (*AddFightCardReq) ProtoMessage()    {}

func (m *AddFightCardReq) GetCardId() int32 {
	if m != nil && m.CardId != nil {
		return *m.CardId
	}
	return 0
}

func (m *AddFightCardReq) GetCard() []*PbItemInfo {
	if m != nil {
		return m.Card
	}
	return nil
}

// 删除卡组卡牌请求
type DelFightCardReq struct {
	CardId           *int32        `protobuf:"varint,2,opt,name=cardId" json:"cardId,omitempty"`
	Card             []*PbItemInfo `protobuf:"bytes,1,rep,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *DelFightCardReq) Reset()         { *m = DelFightCardReq{} }
func (m *DelFightCardReq) String() string { return proto.CompactTextString(m) }
func (*DelFightCardReq) ProtoMessage()    {}

func (m *DelFightCardReq) GetCardId() int32 {
	if m != nil && m.CardId != nil {
		return *m.CardId
	}
	return 0
}

func (m *DelFightCardReq) GetCard() []*PbItemInfo {
	if m != nil {
		return m.Card
	}
	return nil
}

// 添加抽取卡牌请求
type ExtractCardReq struct {
	ExtractCardType  *int32 `protobuf:"varint,1,opt,name=ExtractCardType" json:"ExtractCardType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ExtractCardReq) Reset()         { *m = ExtractCardReq{} }
func (m *ExtractCardReq) String() string { return proto.CompactTextString(m) }
func (*ExtractCardReq) ProtoMessage()    {}

func (m *ExtractCardReq) GetExtractCardType() int32 {
	if m != nil && m.ExtractCardType != nil {
		return *m.ExtractCardType
	}
	return 0
}

// 添加抽取卡牌响应
type ExtractCardRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExtractCardRsp) Reset()         { *m = ExtractCardRsp{} }
func (m *ExtractCardRsp) String() string { return proto.CompactTextString(m) }
func (*ExtractCardRsp) ProtoMessage()    {}

func (m *ExtractCardRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 添加领取抽卡赠送的卡牌请求
type ReceiveCardReq struct {
	ReceiveCardType  *int32 `protobuf:"varint,1,opt,name=ReceiveCardType" json:"ReceiveCardType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReceiveCardReq) Reset()         { *m = ReceiveCardReq{} }
func (m *ReceiveCardReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveCardReq) ProtoMessage()    {}

func (m *ReceiveCardReq) GetReceiveCardType() int32 {
	if m != nil && m.ReceiveCardType != nil {
		return *m.ReceiveCardType
	}
	return 0
}

// 添加领取抽卡赠送的卡牌响应
type ReceiveCardRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReceiveCardRsp) Reset()         { *m = ReceiveCardRsp{} }
func (m *ReceiveCardRsp) String() string { return proto.CompactTextString(m) }
func (*ReceiveCardRsp) ProtoMessage()    {}

func (m *ReceiveCardRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 添加抽取技能卡牌请求
type ExtractSkillCardReq struct {
	ExtractSkillCardType *int32 `protobuf:"varint,1,opt,name=ExtractSkillCardType" json:"ExtractSkillCardType,omitempty"`
	XXX_unrecognized     []byte `json:"-"`
}

func (m *ExtractSkillCardReq) Reset()         { *m = ExtractSkillCardReq{} }
func (m *ExtractSkillCardReq) String() string { return proto.CompactTextString(m) }
func (*ExtractSkillCardReq) ProtoMessage()    {}

func (m *ExtractSkillCardReq) GetExtractSkillCardType() int32 {
	if m != nil && m.ExtractSkillCardType != nil {
		return *m.ExtractSkillCardType
	}
	return 0
}

// 添加抽取技能卡牌响应
type ExtractSkillCardRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExtractSkillCardRsp) Reset()         { *m = ExtractSkillCardRsp{} }
func (m *ExtractSkillCardRsp) String() string { return proto.CompactTextString(m) }
func (*ExtractSkillCardRsp) ProtoMessage()    {}

func (m *ExtractSkillCardRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 添加获取抽卡和奖励信息请求
// 添加获取抽卡和奖励信息响应
type GetBuyCardCardInfoRsp struct {
	Info             *RespondInfo     `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	CostGoldNum      *int32           `protobuf:"varint,2,opt,name=costGoldNum" json:"costGoldNum,omitempty"`
	BuyCardInfo      []*PbBuyCardInfo `protobuf:"bytes,3,rep,name=buyCardInfo" json:"buyCardInfo,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetBuyCardCardInfoRsp) Reset()         { *m = GetBuyCardCardInfoRsp{} }
func (m *GetBuyCardCardInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetBuyCardCardInfoRsp) ProtoMessage()    {}

func (m *GetBuyCardCardInfoRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetBuyCardCardInfoRsp) GetCostGoldNum() int32 {
	if m != nil && m.CostGoldNum != nil {
		return *m.CostGoldNum
	}
	return 0
}

func (m *GetBuyCardCardInfoRsp) GetBuyCardInfo() []*PbBuyCardInfo {
	if m != nil {
		return m.BuyCardInfo
	}
	return nil
}
