// Code generated by protoc-gen-go.
// source: chapter.proto
// DO NOT EDIT!

package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 关卡信息
type PbLevelInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pass             *int32 `protobuf:"varint,2,opt,name=pass" json:"pass,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PbLevelInfo) Reset()         { *m = PbLevelInfo{} }
func (m *PbLevelInfo) String() string { return proto.CompactTextString(m) }
func (*PbLevelInfo) ProtoMessage()    {}

func (m *PbLevelInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PbLevelInfo) GetPass() int32 {
	if m != nil && m.Pass != nil {
		return *m.Pass
	}
	return 0
}

// 读取章节关卡信息请求
type GetLevelInfoReq struct {
	ChapterId        *int32 `protobuf:"varint,1,opt,name=chapterId" json:"chapterId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetLevelInfoReq) Reset()         { *m = GetLevelInfoReq{} }
func (m *GetLevelInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetLevelInfoReq) ProtoMessage()    {}

func (m *GetLevelInfoReq) GetChapterId() int32 {
	if m != nil && m.ChapterId != nil {
		return *m.ChapterId
	}
	return 0
}

// 读取章节关卡信息响应
type GetLevelInfoRsp struct {
	Info             *RespondInfo   `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Levels           []*PbLevelInfo `protobuf:"bytes,2,rep,name=levels" json:"levels,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetLevelInfoRsp) Reset()         { *m = GetLevelInfoRsp{} }
func (m *GetLevelInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetLevelInfoRsp) ProtoMessage()    {}

func (m *GetLevelInfoRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetLevelInfoRsp) GetLevels() []*PbLevelInfo {
	if m != nil {
		return m.Levels
	}
	return nil
}

// 关卡信息
type PbPointInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PassCnt          *int32 `protobuf:"varint,2,opt,name=passCnt" json:"passCnt,omitempty"`
	FightCnt         *int32 `protobuf:"varint,3,opt,name=fightCnt" json:"fightCnt,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PbPointInfo) Reset()         { *m = PbPointInfo{} }
func (m *PbPointInfo) String() string { return proto.CompactTextString(m) }
func (*PbPointInfo) ProtoMessage()    {}

func (m *PbPointInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PbPointInfo) GetPassCnt() int32 {
	if m != nil && m.PassCnt != nil {
		return *m.PassCnt
	}
	return 0
}

func (m *PbPointInfo) GetFightCnt() int32 {
	if m != nil && m.FightCnt != nil {
		return *m.FightCnt
	}
	return 0
}

// 读取关卡战斗点信息请求
type GetPointInfoReq struct {
	ChapterId        *int32 `protobuf:"varint,1,opt,name=chapterId" json:"chapterId,omitempty"`
	LevelId          *int32 `protobuf:"varint,2,opt,name=levelId" json:"levelId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetPointInfoReq) Reset()         { *m = GetPointInfoReq{} }
func (m *GetPointInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetPointInfoReq) ProtoMessage()    {}

func (m *GetPointInfoReq) GetChapterId() int32 {
	if m != nil && m.ChapterId != nil {
		return *m.ChapterId
	}
	return 0
}

func (m *GetPointInfoReq) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// 读取关卡战斗点信息响应
type GetPointInfoRsp struct {
	Info             *RespondInfo   `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Points           []*PbPointInfo `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetPointInfoRsp) Reset()         { *m = GetPointInfoRsp{} }
func (m *GetPointInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetPointInfoRsp) ProtoMessage()    {}

func (m *GetPointInfoRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetPointInfoRsp) GetPoints() []*PbPointInfo {
	if m != nil {
		return m.Points
	}
	return nil
}

// 战斗洗牌请求
// NULL
// 战斗洗牌请求
type ChapterShuffleRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ChapterShuffleRsp) Reset()         { *m = ChapterShuffleRsp{} }
func (m *ChapterShuffleRsp) String() string { return proto.CompactTextString(m) }
func (*ChapterShuffleRsp) ProtoMessage()    {}

func (m *ChapterShuffleRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 征战战斗开始请求
type ChapterBattleBeginReq struct {
	ChapterId        *int32 `protobuf:"varint,1,opt,name=chapterId" json:"chapterId,omitempty"`
	LevelId          *int32 `protobuf:"varint,2,opt,name=levelId" json:"levelId,omitempty"`
	PointId          *int32 `protobuf:"varint,3,opt,name=pointId" json:"pointId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChapterBattleBeginReq) Reset()         { *m = ChapterBattleBeginReq{} }
func (m *ChapterBattleBeginReq) String() string { return proto.CompactTextString(m) }
func (*ChapterBattleBeginReq) ProtoMessage()    {}

func (m *ChapterBattleBeginReq) GetChapterId() int32 {
	if m != nil && m.ChapterId != nil {
		return *m.ChapterId
	}
	return 0
}

func (m *ChapterBattleBeginReq) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

func (m *ChapterBattleBeginReq) GetPointId() int32 {
	if m != nil && m.PointId != nil {
		return *m.PointId
	}
	return 0
}

// 征战战斗开始响应
type ChapterBattleBeginRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ChapterBattleBeginRsp) Reset()         { *m = ChapterBattleBeginRsp{} }
func (m *ChapterBattleBeginRsp) String() string { return proto.CompactTextString(m) }
func (*ChapterBattleBeginRsp) ProtoMessage()    {}

func (m *ChapterBattleBeginRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 征战战斗结束请求
type ChapterBattleEndReq struct {
	Win              *int32 `protobuf:"varint,1,opt,name=win" json:"win,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChapterBattleEndReq) Reset()         { *m = ChapterBattleEndReq{} }
func (m *ChapterBattleEndReq) String() string { return proto.CompactTextString(m) }
func (*ChapterBattleEndReq) ProtoMessage()    {}

func (m *ChapterBattleEndReq) GetWin() int32 {
	if m != nil && m.Win != nil {
		return *m.Win
	}
	return 0
}

// 征战战斗结束响应
type ChapterBattleEndRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	ChapterId        *int32       `protobuf:"varint,2,opt,name=chapterId" json:"chapterId,omitempty"`
	LevelId          *int32       `protobuf:"varint,3,opt,name=levelId" json:"levelId,omitempty"`
	PointId          *int32       `protobuf:"varint,4,opt,name=pointId" json:"pointId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ChapterBattleEndRsp) Reset()         { *m = ChapterBattleEndRsp{} }
func (m *ChapterBattleEndRsp) String() string { return proto.CompactTextString(m) }
func (*ChapterBattleEndRsp) ProtoMessage()    {}

func (m *ChapterBattleEndRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ChapterBattleEndRsp) GetChapterId() int32 {
	if m != nil && m.ChapterId != nil {
		return *m.ChapterId
	}
	return 0
}

func (m *ChapterBattleEndRsp) GetLevelId() int32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

func (m *ChapterBattleEndRsp) GetPointId() int32 {
	if m != nil && m.PointId != nil {
		return *m.PointId
	}
	return 0
}
