// Code generated by protoc-gen-go.
// source: equipment.proto
// DO NOT EDIT!

package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 强化或提升品质请求
type StrengthenEquipmentReq struct {
	Strengthen       *int32  `protobuf:"varint,1,opt,name=strengthen" json:"strengthen,omitempty"`
	Eid              *int32  `protobuf:"varint,2,opt,name=eid" json:"eid,omitempty"`
	Indx             *int32  `protobuf:"varint,3,opt,name=indx" json:"indx,omitempty"`
	ConsumeIndex     []int32 `protobuf:"varint,4,rep,name=ConsumeIndex" json:"ConsumeIndex,omitempty"`
	AddProbability   *int32  `protobuf:"varint,5,opt,name=addProbability" json:"addProbability,omitempty"`
	NotLeveldown     *int32  `protobuf:"varint,6,opt,name=notLeveldown" json:"notLeveldown,omitempty"`
	GoldColorup      *int32  `protobuf:"varint,7,opt,name=goldColorup" json:"goldColorup,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StrengthenEquipmentReq) Reset()         { *m = StrengthenEquipmentReq{} }
func (m *StrengthenEquipmentReq) String() string { return proto.CompactTextString(m) }
func (*StrengthenEquipmentReq) ProtoMessage()    {}

func (m *StrengthenEquipmentReq) GetStrengthen() int32 {
	if m != nil && m.Strengthen != nil {
		return *m.Strengthen
	}
	return 0
}

func (m *StrengthenEquipmentReq) GetEid() int32 {
	if m != nil && m.Eid != nil {
		return *m.Eid
	}
	return 0
}

func (m *StrengthenEquipmentReq) GetIndx() int32 {
	if m != nil && m.Indx != nil {
		return *m.Indx
	}
	return 0
}

func (m *StrengthenEquipmentReq) GetConsumeIndex() []int32 {
	if m != nil {
		return m.ConsumeIndex
	}
	return nil
}

func (m *StrengthenEquipmentReq) GetAddProbability() int32 {
	if m != nil && m.AddProbability != nil {
		return *m.AddProbability
	}
	return 0
}

func (m *StrengthenEquipmentReq) GetNotLeveldown() int32 {
	if m != nil && m.NotLeveldown != nil {
		return *m.NotLeveldown
	}
	return 0
}

func (m *StrengthenEquipmentReq) GetGoldColorup() int32 {
	if m != nil && m.GoldColorup != nil {
		return *m.GoldColorup
	}
	return 0
}

// 强化或提升品质响应
type StrengthenEquipmentRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Result           *int32       `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	Equip            *PbItemInfo  `protobuf:"bytes,3,opt,name=equip" json:"equip,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StrengthenEquipmentRsp) Reset()         { *m = StrengthenEquipmentRsp{} }
func (m *StrengthenEquipmentRsp) String() string { return proto.CompactTextString(m) }
func (*StrengthenEquipmentRsp) ProtoMessage()    {}

func (m *StrengthenEquipmentRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *StrengthenEquipmentRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *StrengthenEquipmentRsp) GetEquip() *PbItemInfo {
	if m != nil {
		return m.Equip
	}
	return nil
}

// 更换装备请求
type ReplaceEquipmentReq struct {
	Indx             *int32 `protobuf:"varint,1,opt,name=indx" json:"indx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReplaceEquipmentReq) Reset()         { *m = ReplaceEquipmentReq{} }
func (m *ReplaceEquipmentReq) String() string { return proto.CompactTextString(m) }
func (*ReplaceEquipmentReq) ProtoMessage()    {}

func (m *ReplaceEquipmentReq) GetIndx() int32 {
	if m != nil && m.Indx != nil {
		return *m.Indx
	}
	return 0
}

// 更换装备响应
type ReplaceEquipmentRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReplaceEquipmentRsp) Reset()         { *m = ReplaceEquipmentRsp{} }
func (m *ReplaceEquipmentRsp) String() string { return proto.CompactTextString(m) }
func (*ReplaceEquipmentRsp) ProtoMessage()    {}

func (m *ReplaceEquipmentRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 卸下装备请求
type UnloadEquipmentReq struct {
	Eid              *int32 `protobuf:"varint,1,opt,name=eid" json:"eid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnloadEquipmentReq) Reset()         { *m = UnloadEquipmentReq{} }
func (m *UnloadEquipmentReq) String() string { return proto.CompactTextString(m) }
func (*UnloadEquipmentReq) ProtoMessage()    {}

func (m *UnloadEquipmentReq) GetEid() int32 {
	if m != nil && m.Eid != nil {
		return *m.Eid
	}
	return 0
}

// 卸下装备响应
type UnloadEquipmentRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Indx             *int32       `protobuf:"varint,2,opt,name=indx" json:"indx,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *UnloadEquipmentRsp) Reset()         { *m = UnloadEquipmentRsp{} }
func (m *UnloadEquipmentRsp) String() string { return proto.CompactTextString(m) }
func (*UnloadEquipmentRsp) ProtoMessage()    {}

func (m *UnloadEquipmentRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *UnloadEquipmentRsp) GetIndx() int32 {
	if m != nil && m.Indx != nil {
		return *m.Indx
	}
	return 0
}
