// Code generated by protoc-gen-go.
// source: friend.proto
// DO NOT EDIT!

package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 获取好友列表请求
// NULL
// 获取好友列表响应
type GetFriendRsp struct {
	Info *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Ts   *int32       `protobuf:"varint,2,opt,name=ts" json:"ts,omitempty"`
	Cnt  *int32       `protobuf:"varint,3,opt,name=cnt" json:"cnt,omitempty"`
	// 返回id,name,vocationId,expr,FightValue,online等字段
	Unaccepts        []*RoleCommonInfo `protobuf:"bytes,4,rep,name=unaccepts" json:"unaccepts,omitempty"`
	Accepts          []*RoleCommonInfo `protobuf:"bytes,5,rep,name=accepts" json:"accepts,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetFriendRsp) Reset()         { *m = GetFriendRsp{} }
func (m *GetFriendRsp) String() string { return proto.CompactTextString(m) }
func (*GetFriendRsp) ProtoMessage()    {}

func (m *GetFriendRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetFriendRsp) GetTs() int32 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *GetFriendRsp) GetCnt() int32 {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return 0
}

func (m *GetFriendRsp) GetUnaccepts() []*RoleCommonInfo {
	if m != nil {
		return m.Unaccepts
	}
	return nil
}

func (m *GetFriendRsp) GetAccepts() []*RoleCommonInfo {
	if m != nil {
		return m.Accepts
	}
	return nil
}

// 获取推荐好友列表请求
// NULL
// 获取推荐好友列表响应
type GetReferrerRsp struct {
	Info *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	// 返回id,name,vocationId,expr,FightValue,online等字段
	Roles            []*RoleCommonInfo `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetReferrerRsp) Reset()         { *m = GetReferrerRsp{} }
func (m *GetReferrerRsp) String() string { return proto.CompactTextString(m) }
func (*GetReferrerRsp) ProtoMessage()    {}

func (m *GetReferrerRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetReferrerRsp) GetRoles() []*RoleCommonInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

// 添加好友请求
type AddFriendReq struct {
	RoleId           []int32  `protobuf:"varint,1,rep,name=roleId" json:"roleId,omitempty"`
	RoleName         []string `protobuf:"bytes,2,rep,name=roleName" json:"roleName,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AddFriendReq) Reset()         { *m = AddFriendReq{} }
func (m *AddFriendReq) String() string { return proto.CompactTextString(m) }
func (*AddFriendReq) ProtoMessage()    {}

func (m *AddFriendReq) GetRoleId() []int32 {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *AddFriendReq) GetRoleName() []string {
	if m != nil {
		return m.RoleName
	}
	return nil
}

// 添加好友通知
type AddFriendNotify struct {
	Info             *RespondInfo      `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Roles            []*RoleCommonInfo `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *AddFriendNotify) Reset()         { *m = AddFriendNotify{} }
func (m *AddFriendNotify) String() string { return proto.CompactTextString(m) }
func (*AddFriendNotify) ProtoMessage()    {}

func (m *AddFriendNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *AddFriendNotify) GetRoles() []*RoleCommonInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

// 同意或者拒绝添加好友请求
type DealFriendReq struct {
	RoleId           []int32 `protobuf:"varint,1,rep,name=roleId" json:"roleId,omitempty"`
	Agree            *int32  `protobuf:"varint,2,opt,name=agree" json:"agree,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DealFriendReq) Reset()         { *m = DealFriendReq{} }
func (m *DealFriendReq) String() string { return proto.CompactTextString(m) }
func (*DealFriendReq) ProtoMessage()    {}

func (m *DealFriendReq) GetRoleId() []int32 {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *DealFriendReq) GetAgree() int32 {
	if m != nil && m.Agree != nil {
		return *m.Agree
	}
	return 0
}

// 同意或者拒绝添加好友通知
type DealFriendNotify struct {
	Info             *RespondInfo      `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RoleId           []int32           `protobuf:"varint,2,rep,name=roleId" json:"roleId,omitempty"`
	Agree            *int32            `protobuf:"varint,3,opt,name=agree" json:"agree,omitempty"`
	Roles            []*RoleCommonInfo `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DealFriendNotify) Reset()         { *m = DealFriendNotify{} }
func (m *DealFriendNotify) String() string { return proto.CompactTextString(m) }
func (*DealFriendNotify) ProtoMessage()    {}

func (m *DealFriendNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DealFriendNotify) GetRoleId() []int32 {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *DealFriendNotify) GetAgree() int32 {
	if m != nil && m.Agree != nil {
		return *m.Agree
	}
	return 0
}

func (m *DealFriendNotify) GetRoles() []*RoleCommonInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

// 删除好友请求
type DeleteFriendReq struct {
	RoleId           *int32 `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteFriendReq) Reset()         { *m = DeleteFriendReq{} }
func (m *DeleteFriendReq) String() string { return proto.CompactTextString(m) }
func (*DeleteFriendReq) ProtoMessage()    {}

func (m *DeleteFriendReq) GetRoleId() int32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

// 删除好友通知
type DeleteFriendNotify struct {
	Roles            []*RoleCommonInfo `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeleteFriendNotify) Reset()         { *m = DeleteFriendNotify{} }
func (m *DeleteFriendNotify) String() string { return proto.CompactTextString(m) }
func (*DeleteFriendNotify) ProtoMessage()    {}

func (m *DeleteFriendNotify) GetRoles() []*RoleCommonInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

// 赠送物品请求
type FriendSendReq struct {
	RoleId           *int32 `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendSendReq) Reset()         { *m = FriendSendReq{} }
func (m *FriendSendReq) String() string { return proto.CompactTextString(m) }
func (*FriendSendReq) ProtoMessage()    {}

func (m *FriendSendReq) GetRoleId() int32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

// 赠送物品通知
type FriendSendNotify struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RoleId           []int32      `protobuf:"varint,2,rep,name=roleId" json:"roleId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FriendSendNotify) Reset()         { *m = FriendSendNotify{} }
func (m *FriendSendNotify) String() string { return proto.CompactTextString(m) }
func (*FriendSendNotify) ProtoMessage()    {}

func (m *FriendSendNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *FriendSendNotify) GetRoleId() []int32 {
	if m != nil {
		return m.RoleId
	}
	return nil
}

// 领取赠送物品请求
type FriendRecvReq struct {
	RoleId           *int32 `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendRecvReq) Reset()         { *m = FriendRecvReq{} }
func (m *FriendRecvReq) String() string { return proto.CompactTextString(m) }
func (*FriendRecvReq) ProtoMessage()    {}

func (m *FriendRecvReq) GetRoleId() int32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

// 领取赠送物品响应
type FriendRecvRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FriendRecvRsp) Reset()         { *m = FriendRecvRsp{} }
func (m *FriendRecvRsp) String() string { return proto.CompactTextString(m) }
func (*FriendRecvRsp) ProtoMessage()    {}

func (m *FriendRecvRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 好友状态变更通知
type FriendInfoChangeNotify struct {
	Info             *RespondInfo      `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Roles            []*RoleCommonInfo `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *FriendInfoChangeNotify) Reset()         { *m = FriendInfoChangeNotify{} }
func (m *FriendInfoChangeNotify) String() string { return proto.CompactTextString(m) }
func (*FriendInfoChangeNotify) ProtoMessage()    {}

func (m *FriendInfoChangeNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *FriendInfoChangeNotify) GetRoles() []*RoleCommonInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}
