// Code generated by protoc-gen-go.
// source: mail.proto
// DO NOT EDIT!

package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 邮件详细信息
type PbMailInfo struct {
	Id               *int32        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sender           *string       `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	Ts               *int32        `protobuf:"varint,3,opt,name=ts" json:"ts,omitempty"`
	Title            *string       `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Text             *string       `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	Items            []*PbItemInfo `protobuf:"bytes,6,rep,name=items" json:"items,omitempty"`
	Read             *int32        `protobuf:"varint,7,opt,name=read" json:"read,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PbMailInfo) Reset()         { *m = PbMailInfo{} }
func (m *PbMailInfo) String() string { return proto.CompactTextString(m) }
func (*PbMailInfo) ProtoMessage()    {}

func (m *PbMailInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PbMailInfo) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *PbMailInfo) GetTs() int32 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *PbMailInfo) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PbMailInfo) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *PbMailInfo) GetItems() []*PbItemInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PbMailInfo) GetRead() int32 {
	if m != nil && m.Read != nil {
		return *m.Read
	}
	return 0
}

// 读取邮件列表响应
type GetMailListRsp struct {
	Info             *RespondInfo  `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Mails            []*PbMailInfo `protobuf:"bytes,2,rep,name=mails" json:"mails,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GetMailListRsp) Reset()         { *m = GetMailListRsp{} }
func (m *GetMailListRsp) String() string { return proto.CompactTextString(m) }
func (*GetMailListRsp) ProtoMessage()    {}

func (m *GetMailListRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetMailListRsp) GetMails() []*PbMailInfo {
	if m != nil {
		return m.Mails
	}
	return nil
}

// 阅读邮件请求
type ReadMailReq struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReadMailReq) Reset()         { *m = ReadMailReq{} }
func (m *ReadMailReq) String() string { return proto.CompactTextString(m) }
func (*ReadMailReq) ProtoMessage()    {}

func (m *ReadMailReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 领取(删除)邮件请求(有物品的邮件，领取之后就直接删除，没有物品的直接删除)
type GetMailItemReq struct {
	Id               []int32 `protobuf:"varint,1,rep,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetMailItemReq) Reset()         { *m = GetMailItemReq{} }
func (m *GetMailItemReq) String() string { return proto.CompactTextString(m) }
func (*GetMailItemReq) ProtoMessage()    {}

func (m *GetMailItemReq) GetId() []int32 {
	if m != nil {
		return m.Id
	}
	return nil
}

// 领取(删除)邮件响应
type GetMailItemRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetMailItemRsp) Reset()         { *m = GetMailItemRsp{} }
func (m *GetMailItemRsp) String() string { return proto.CompactTextString(m) }
func (*GetMailItemRsp) ProtoMessage()    {}

func (m *GetMailItemRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 新邮件通知
type NewMailNotify struct {
	Info             *RespondInfo  `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Mails            []*PbMailInfo `protobuf:"bytes,2,rep,name=mails" json:"mails,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *NewMailNotify) Reset()         { *m = NewMailNotify{} }
func (m *NewMailNotify) String() string { return proto.CompactTextString(m) }
func (*NewMailNotify) ProtoMessage()    {}

func (m *NewMailNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *NewMailNotify) GetMails() []*PbMailInfo {
	if m != nil {
		return m.Mails
	}
	return nil
}
