// Code generated by protoc-gen-go.
// source: role.proto
// DO NOT EDIT!

package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetRoleListReq struct {
	Info             *RequestInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetRoleListReq) Reset()         { *m = GetRoleListReq{} }
func (m *GetRoleListReq) String() string { return proto.CompactTextString(m) }
func (*GetRoleListReq) ProtoMessage()    {}

func (m *GetRoleListReq) GetInfo() *RequestInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetRoleListRsp struct {
	Info             *RespondInfo      `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Roles            []*RoleCommonInfo `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	ServerTs         *int32            `protobuf:"varint,3,opt,name=serverTs" json:"serverTs,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetRoleListRsp) Reset()         { *m = GetRoleListRsp{} }
func (m *GetRoleListRsp) String() string { return proto.CompactTextString(m) }
func (*GetRoleListRsp) ProtoMessage()    {}

func (m *GetRoleListRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetRoleListRsp) GetRoles() []*RoleCommonInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *GetRoleListRsp) GetServerTs() int32 {
	if m != nil && m.ServerTs != nil {
		return *m.ServerTs
	}
	return 0
}

type SelectRoleReq struct {
	Info             *RequestInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RoleId           *int32       `protobuf:"varint,2,opt,name=roleId" json:"roleId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SelectRoleReq) Reset()         { *m = SelectRoleReq{} }
func (m *SelectRoleReq) String() string { return proto.CompactTextString(m) }
func (*SelectRoleReq) ProtoMessage()    {}

func (m *SelectRoleReq) GetInfo() *RequestInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *SelectRoleReq) GetRoleId() int32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

type SelectRoleRsp struct {
	Info             *RespondInfo        `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Role             *RoleCommonInfo     `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	Bag              *PbBagInfo          `protobuf:"bytes,3,opt,name=bag" json:"bag,omitempty"`
	CardBag          *PbCardBagInfo      `protobuf:"bytes,4,opt,name=cardBag" json:"cardBag,omitempty"`
	FightCardBag     *PbFightCardBagInfo `protobuf:"bytes,5,opt,name=fightCardBag" json:"fightCardBag,omitempty"`
	Other            *RoleOtherInfo      `protobuf:"bytes,6,opt,name=other" json:"other,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *SelectRoleRsp) Reset()         { *m = SelectRoleRsp{} }
func (m *SelectRoleRsp) String() string { return proto.CompactTextString(m) }
func (*SelectRoleRsp) ProtoMessage()    {}

func (m *SelectRoleRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *SelectRoleRsp) GetRole() *RoleCommonInfo {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *SelectRoleRsp) GetBag() *PbBagInfo {
	if m != nil {
		return m.Bag
	}
	return nil
}

func (m *SelectRoleRsp) GetCardBag() *PbCardBagInfo {
	if m != nil {
		return m.CardBag
	}
	return nil
}

func (m *SelectRoleRsp) GetFightCardBag() *PbFightCardBagInfo {
	if m != nil {
		return m.FightCardBag
	}
	return nil
}

func (m *SelectRoleRsp) GetOther() *RoleOtherInfo {
	if m != nil {
		return m.Other
	}
	return nil
}

type CreateRoleReq struct {
	Info             *RequestInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Name             *string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sex              *int32       `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CreateRoleReq) Reset()         { *m = CreateRoleReq{} }
func (m *CreateRoleReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoleReq) ProtoMessage()    {}

func (m *CreateRoleReq) GetInfo() *RequestInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *CreateRoleReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateRoleReq) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

type CreateRoleRsp struct {
	Info             *RespondInfo        `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Role             *RoleCommonInfo     `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	Bag              *PbBagInfo          `protobuf:"bytes,3,opt,name=bag" json:"bag,omitempty"`
	CardBag          *PbCardBagInfo      `protobuf:"bytes,4,opt,name=cardBag" json:"cardBag,omitempty"`
	FightCardBag     *PbFightCardBagInfo `protobuf:"bytes,5,opt,name=fightCardBag" json:"fightCardBag,omitempty"`
	Other            *RoleOtherInfo      `protobuf:"bytes,6,opt,name=other" json:"other,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *CreateRoleRsp) Reset()         { *m = CreateRoleRsp{} }
func (m *CreateRoleRsp) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRsp) ProtoMessage()    {}

func (m *CreateRoleRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *CreateRoleRsp) GetRole() *RoleCommonInfo {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *CreateRoleRsp) GetBag() *PbBagInfo {
	if m != nil {
		return m.Bag
	}
	return nil
}

func (m *CreateRoleRsp) GetCardBag() *PbCardBagInfo {
	if m != nil {
		return m.CardBag
	}
	return nil
}

func (m *CreateRoleRsp) GetFightCardBag() *PbFightCardBagInfo {
	if m != nil {
		return m.FightCardBag
	}
	return nil
}

func (m *CreateRoleRsp) GetOther() *RoleOtherInfo {
	if m != nil {
		return m.Other
	}
	return nil
}

// 角色体力恢复通知
type PowerAddNotify struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PowerAddNotify) Reset()         { *m = PowerAddNotify{} }
func (m *PowerAddNotify) String() string { return proto.CompactTextString(m) }
func (*PowerAddNotify) ProtoMessage()    {}

func (m *PowerAddNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 购买体力请求
// NULL
// 购买免费体力请求
type BuyPowerRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	BuyPowerCnt      *int32       `protobuf:"varint,2,opt,name=buyPowerCnt" json:"buyPowerCnt,omitempty"`
	BuyPowerTs       *int64       `protobuf:"varint,3,opt,name=buyPowerTs" json:"buyPowerTs,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *BuyPowerRsp) Reset()         { *m = BuyPowerRsp{} }
func (m *BuyPowerRsp) String() string { return proto.CompactTextString(m) }
func (*BuyPowerRsp) ProtoMessage()    {}

func (m *BuyPowerRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *BuyPowerRsp) GetBuyPowerCnt() int32 {
	if m != nil && m.BuyPowerCnt != nil {
		return *m.BuyPowerCnt
	}
	return 0
}

func (m *BuyPowerRsp) GetBuyPowerTs() int64 {
	if m != nil && m.BuyPowerTs != nil {
		return *m.BuyPowerTs
	}
	return 0
}

// 领取免费体力请求
// NULL
// 领取免费体力请求
type GetFreePowerRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	GetFreePowerTs   *int64       `protobuf:"varint,2,opt,name=getFreePowerTs" json:"getFreePowerTs,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetFreePowerRsp) Reset()         { *m = GetFreePowerRsp{} }
func (m *GetFreePowerRsp) String() string { return proto.CompactTextString(m) }
func (*GetFreePowerRsp) ProtoMessage()    {}

func (m *GetFreePowerRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetFreePowerRsp) GetGetFreePowerTs() int64 {
	if m != nil && m.GetFreePowerTs != nil {
		return *m.GetFreePowerTs
	}
	return 0
}

// 角色信息变更通知
type InfoChangeNotify struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *InfoChangeNotify) Reset()         { *m = InfoChangeNotify{} }
func (m *InfoChangeNotify) String() string { return proto.CompactTextString(m) }
func (*InfoChangeNotify) ProtoMessage()    {}

func (m *InfoChangeNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 发送聊天消息请求
type SendChatReq struct {
	Type             *int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	RoleId           *int32  `protobuf:"varint,2,opt,name=roleId" json:"roleId,omitempty"`
	Text             *string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendChatReq) Reset()         { *m = SendChatReq{} }
func (m *SendChatReq) String() string { return proto.CompactTextString(m) }
func (*SendChatReq) ProtoMessage()    {}

func (m *SendChatReq) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *SendChatReq) GetRoleId() int32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *SendChatReq) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

// 新聊天消息通知
type NewChatNotify struct {
	Type             *int32          `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Role             *RoleCommonInfo `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	Ts               *int64          `protobuf:"varint,3,opt,name=ts" json:"ts,omitempty"`
	Text             *string         `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *NewChatNotify) Reset()         { *m = NewChatNotify{} }
func (m *NewChatNotify) String() string { return proto.CompactTextString(m) }
func (*NewChatNotify) ProtoMessage()    {}

func (m *NewChatNotify) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *NewChatNotify) GetRole() *RoleCommonInfo {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *NewChatNotify) GetTs() int64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *NewChatNotify) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

// 选择职业请求
type SelectVocationReq struct {
	VocationId       *int32 `protobuf:"varint,1,opt,name=vocationId" json:"vocationId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SelectVocationReq) Reset()         { *m = SelectVocationReq{} }
func (m *SelectVocationReq) String() string { return proto.CompactTextString(m) }
func (*SelectVocationReq) ProtoMessage()    {}

func (m *SelectVocationReq) GetVocationId() int32 {
	if m != nil && m.VocationId != nil {
		return *m.VocationId
	}
	return 0
}

// 获取玩家战斗信息请求
type GetRoleFightInfoReq struct {
	RoleId           *int32 `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRoleFightInfoReq) Reset()         { *m = GetRoleFightInfoReq{} }
func (m *GetRoleFightInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetRoleFightInfoReq) ProtoMessage()    {}

func (m *GetRoleFightInfoReq) GetRoleId() int32 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

// 获取玩家战斗信息响应
type GetRoleFightInfoRsp struct {
	Info             *RespondInfo        `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Role             *RoleCommonInfo     `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	FightCardBag     *PbFightCardBagInfo `protobuf:"bytes,5,opt,name=fightCardBag" json:"fightCardBag,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetRoleFightInfoRsp) Reset()         { *m = GetRoleFightInfoRsp{} }
func (m *GetRoleFightInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetRoleFightInfoRsp) ProtoMessage()    {}

func (m *GetRoleFightInfoRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetRoleFightInfoRsp) GetRole() *RoleCommonInfo {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *GetRoleFightInfoRsp) GetFightCardBag() *PbFightCardBagInfo {
	if m != nil {
		return m.FightCardBag
	}
	return nil
}

// 充值请求
type RechargeReq struct {
	RechargeType     *int32 `protobuf:"varint,1,opt,name=rechargeType" json:"rechargeType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RechargeReq) Reset()         { *m = RechargeReq{} }
func (m *RechargeReq) String() string { return proto.CompactTextString(m) }
func (*RechargeReq) ProtoMessage()    {}

func (m *RechargeReq) GetRechargeType() int32 {
	if m != nil && m.RechargeType != nil {
		return *m.RechargeType
	}
	return 0
}

// 充值到账通知
type RechargeNotify struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RechargeType     *int32       `protobuf:"varint,2,opt,name=rechargeType" json:"rechargeType,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RechargeNotify) Reset()         { *m = RechargeNotify{} }
func (m *RechargeNotify) String() string { return proto.CompactTextString(m) }
func (*RechargeNotify) ProtoMessage()    {}

func (m *RechargeNotify) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RechargeNotify) GetRechargeType() int32 {
	if m != nil && m.RechargeType != nil {
		return *m.RechargeType
	}
	return 0
}
