// Code generated by protoc-gen-go.
// source: task.proto
// DO NOT EDIT!

package GxProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TaskState struct {
	TaskType                *int32 `protobuf:"varint,1,opt,name=taskType" json:"taskType,omitempty"`
	IsCompleteTaskAndReward *int32 `protobuf:"varint,2,opt,name=isCompleteTaskAndReward" json:"isCompleteTaskAndReward,omitempty"`
	XXX_unrecognized        []byte `json:"-"`
}

func (m *TaskState) Reset()         { *m = TaskState{} }
func (m *TaskState) String() string { return proto.CompactTextString(m) }
func (*TaskState) ProtoMessage()    {}

func (m *TaskState) GetTaskType() int32 {
	if m != nil && m.TaskType != nil {
		return *m.TaskType
	}
	return 0
}

func (m *TaskState) GetIsCompleteTaskAndReward() int32 {
	if m != nil && m.IsCompleteTaskAndReward != nil {
		return *m.IsCompleteTaskAndReward
	}
	return 0
}

type PbTaskInfo struct {
	PlayerLevel         *int32 `protobuf:"varint,1,opt,name=playerLevel" json:"playerLevel,omitempty"`
	PassChapterTs       *int64 `protobuf:"varint,2,opt,name=passChapterTs" json:"passChapterTs,omitempty"`
	PassChapterCnt      *int32 `protobuf:"varint,3,opt,name=passChapterCnt" json:"passChapterCnt,omitempty"`
	BlueHerosCnt        *int32 `protobuf:"varint,4,opt,name=blueHerosCnt" json:"blueHerosCnt,omitempty"`
	PurpleHerosCnt      *int32 `protobuf:"varint,5,opt,name=purpleHerosCnt" json:"purpleHerosCnt,omitempty"`
	OrangeHerosCnt      *int32 `protobuf:"varint,6,opt,name=orangeHerosCnt" json:"orangeHerosCnt,omitempty"`
	ReceiveFreePowerCnt *int32 `protobuf:"varint,7,opt,name=receiveFreePowerCnt" json:"receiveFreePowerCnt,omitempty"`
	BuyPowerCnt         *int32 `protobuf:"varint,8,opt,name=buyPowerCnt" json:"buyPowerCnt,omitempty"`
	SignInDaily         *int32 `protobuf:"varint,9,opt,name=signInDaily" json:"signInDaily,omitempty"`
	SignInMonthCnt      *int32 `protobuf:"varint,10,opt,name=signInMonthCnt" json:"signInMonthCnt,omitempty"`
	MoneyPointCnt       *int32 `protobuf:"varint,11,opt,name=moneyPointCnt" json:"moneyPointCnt,omitempty"`
	CompetitiveDailyCnt *int32 `protobuf:"varint,12,opt,name=competitiveDailyCnt" json:"competitiveDailyCnt,omitempty"`
	CompetitiveTotalCnt *int32 `protobuf:"varint,13,opt,name=competitiveTotalCnt" json:"competitiveTotalCnt,omitempty"`
	IsPassTaskChapter   *int32 `protobuf:"varint,14,opt,name=isPassTaskChapter" json:"isPassTaskChapter,omitempty"`
	XXX_unrecognized    []byte `json:"-"`
}

func (m *PbTaskInfo) Reset()         { *m = PbTaskInfo{} }
func (m *PbTaskInfo) String() string { return proto.CompactTextString(m) }
func (*PbTaskInfo) ProtoMessage()    {}

func (m *PbTaskInfo) GetPlayerLevel() int32 {
	if m != nil && m.PlayerLevel != nil {
		return *m.PlayerLevel
	}
	return 0
}

func (m *PbTaskInfo) GetPassChapterTs() int64 {
	if m != nil && m.PassChapterTs != nil {
		return *m.PassChapterTs
	}
	return 0
}

func (m *PbTaskInfo) GetPassChapterCnt() int32 {
	if m != nil && m.PassChapterCnt != nil {
		return *m.PassChapterCnt
	}
	return 0
}

func (m *PbTaskInfo) GetBlueHerosCnt() int32 {
	if m != nil && m.BlueHerosCnt != nil {
		return *m.BlueHerosCnt
	}
	return 0
}

func (m *PbTaskInfo) GetPurpleHerosCnt() int32 {
	if m != nil && m.PurpleHerosCnt != nil {
		return *m.PurpleHerosCnt
	}
	return 0
}

func (m *PbTaskInfo) GetOrangeHerosCnt() int32 {
	if m != nil && m.OrangeHerosCnt != nil {
		return *m.OrangeHerosCnt
	}
	return 0
}

func (m *PbTaskInfo) GetReceiveFreePowerCnt() int32 {
	if m != nil && m.ReceiveFreePowerCnt != nil {
		return *m.ReceiveFreePowerCnt
	}
	return 0
}

func (m *PbTaskInfo) GetBuyPowerCnt() int32 {
	if m != nil && m.BuyPowerCnt != nil {
		return *m.BuyPowerCnt
	}
	return 0
}

func (m *PbTaskInfo) GetSignInDaily() int32 {
	if m != nil && m.SignInDaily != nil {
		return *m.SignInDaily
	}
	return 0
}

func (m *PbTaskInfo) GetSignInMonthCnt() int32 {
	if m != nil && m.SignInMonthCnt != nil {
		return *m.SignInMonthCnt
	}
	return 0
}

func (m *PbTaskInfo) GetMoneyPointCnt() int32 {
	if m != nil && m.MoneyPointCnt != nil {
		return *m.MoneyPointCnt
	}
	return 0
}

func (m *PbTaskInfo) GetCompetitiveDailyCnt() int32 {
	if m != nil && m.CompetitiveDailyCnt != nil {
		return *m.CompetitiveDailyCnt
	}
	return 0
}

func (m *PbTaskInfo) GetCompetitiveTotalCnt() int32 {
	if m != nil && m.CompetitiveTotalCnt != nil {
		return *m.CompetitiveTotalCnt
	}
	return 0
}

func (m *PbTaskInfo) GetIsPassTaskChapter() int32 {
	if m != nil && m.IsPassTaskChapter != nil {
		return *m.IsPassTaskChapter
	}
	return 0
}

// 读取任务列表响应
type GetTasksListRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Tasks            *PbTaskInfo  `protobuf:"bytes,2,opt,name=tasks" json:"tasks,omitempty"`
	TaskSchedule     []*TaskState `protobuf:"bytes,3,rep,name=taskSchedule" json:"taskSchedule,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetTasksListRsp) Reset()         { *m = GetTasksListRsp{} }
func (m *GetTasksListRsp) String() string { return proto.CompactTextString(m) }
func (*GetTasksListRsp) ProtoMessage()    {}

func (m *GetTasksListRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetTasksListRsp) GetTasks() *PbTaskInfo {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *GetTasksListRsp) GetTaskSchedule() []*TaskState {
	if m != nil {
		return m.TaskSchedule
	}
	return nil
}

// 完成任务和触发新任务通知响应
type CompleteTaskRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	CompleteTaskType []int32      `protobuf:"varint,2,rep,name=completeTaskType" json:"completeTaskType,omitempty"`
	PostTask         []int32      `protobuf:"varint,3,rep,name=postTask" json:"postTask,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CompleteTaskRsp) Reset()         { *m = CompleteTaskRsp{} }
func (m *CompleteTaskRsp) String() string { return proto.CompactTextString(m) }
func (*CompleteTaskRsp) ProtoMessage()    {}

func (m *CompleteTaskRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *CompleteTaskRsp) GetCompleteTaskType() []int32 {
	if m != nil {
		return m.CompleteTaskType
	}
	return nil
}

func (m *CompleteTaskRsp) GetPostTask() []int32 {
	if m != nil {
		return m.PostTask
	}
	return nil
}

// 领取任务奖励请求
type ReceiveTaskRewardReq struct {
	ReceiveTaskRewardType *int32 `protobuf:"varint,1,opt,name=receiveTaskRewardType" json:"receiveTaskRewardType,omitempty"`
	XXX_unrecognized      []byte `json:"-"`
}

func (m *ReceiveTaskRewardReq) Reset()         { *m = ReceiveTaskRewardReq{} }
func (m *ReceiveTaskRewardReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveTaskRewardReq) ProtoMessage()    {}

func (m *ReceiveTaskRewardReq) GetReceiveTaskRewardType() int32 {
	if m != nil && m.ReceiveTaskRewardType != nil {
		return *m.ReceiveTaskRewardType
	}
	return 0
}

// 领取任务奖励响应
type ReceiveTaskRewardRsp struct {
	Info             *RespondInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReceiveTaskRewardRsp) Reset()         { *m = ReceiveTaskRewardRsp{} }
func (m *ReceiveTaskRewardRsp) String() string { return proto.CompactTextString(m) }
func (*ReceiveTaskRewardRsp) ProtoMessage()    {}

func (m *ReceiveTaskRewardRsp) GetInfo() *RespondInfo {
	if m != nil {
		return m.Info
	}
	return nil
}
